#!/bin/bash -e

project_dir="$(cd "$(dirname "$0")/.." && pwd)"
target_dir="$project_dir/target"
echo "Using target dir '$target_dir'"

if [ -d "$target_dir" ]; then
    echo "Removing existing target dir '$target_dir'"
    rm -rf "$target_dir"
fi
echo "Creating target dir '$target_dir'"
mkdir -p "$target_dir"

build() {
    local os="$1"
    local arch="$2"
    local name="$3"
    local os_dir="$target_dir/$os-$arch"
    echo "Building '$os/$arch' distributable '$name' into '$os_dir'"
    mkdir "$os_dir"
    (
        cd "$project_dir"
        GOOS="$os" GOARCH="$arch" go build -o "$os_dir/$name" ./
    )
    (
        cd "$os_dir"
        tar -zcf "$os-$arch.tar.gz" "$name"
    )
}

build "linux" "amd64" "preftime"
build "windows" "amd64" "preftime.exe"
build "darwin" "amd64" "preftime"
